# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vignesh
email: rvignesh@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Copyright &copy; 2016 Vignesh.
  Hosted by [Github](https://github.com/rvignesh89/rvignesh89.github.io) and powered by Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rvignesh89.github.io" # the base hostname & protocol for your site
twitter_username: rvignesh89
github_username:  rvignesh89

# Build settings
markdown: kramdown
